CREATE TABLE dbo.GiphyRequest
(
	ID INT IDENTITY (1, 1) NOT NULL,
	IPAddress NVARCHAR(50) NOT NULL,
	BrowserType NVARCHAR(100) NULL,
	RequestDate DATETIME NOT NULL,
	SearchType NVARCHAR(100) NOT NULL,
	Rating NVARCHAR(20) NOT NULL,
	KeyWord NVARCHAR(100) NULL,
	CONSTRAINT [PK_dbo.GiphyRequest] PRIMARY KEY CLUSTERED (ID ASC)
);
GO